---
apiVersion: v1
kind: Template
metadata:
  labels:
    provider: fabric8
    project: fabric8-online-jenkins
    version: 1.0.91
    group: io.fabric8.online.packages
  name: fabric8-online-jenkins
objects:
- apiVersion: v1
  kind: ProjectRequest
  metadata:
    annotations:
      openshift.io/description: ${PROJECT_DESCRIPTION}
      openshift.io/display-name: ${PROJECT_DISPLAYNAME}
      openshift.io/requester: ${PROJECT_REQUESTING_USER}
    labels:
      provider: fabric8
      project: fabric8-online-team
      version: 1.0.91
      group: io.fabric8.online.packages
    name: ${PROJECT_NAME}
- apiVersion: v1
  kind: RoleBindingRestriction
  metadata:
    name: dsaas-user-access
  spec: 
    userrestriction:
      users: 
      - ${PROJECT_USER}
- apiVersion: v1
  kind: RoleBindingRestriction
  metadata:
    name: dsaas-access-sa-ns
  spec: 
    serviceaccountrestriction:
      namespaces: 
      - ${PROJECT_TEMPLATE_NAME}-jenkins
- apiVersion: v1
  kind: RoleBinding
  metadata:
    labels:
      provider: fabric8
      project: fabric8-online-jenkins
      version: 1.0.91
      group: io.fabric8.online.packages
    name: useradmin
  roleRef:
    name: admin
  subjects:
  - kind: User
    name: ${PROJECT_USER}
  userNames:
  - ${PROJECT_USER}
- apiVersion: v1
  kind: RoleBinding
  metadata:
    labels:
      provider: fabric8
      project: fabric8-online-team
      version: 1.0.91
      group: io.fabric8.online.packages
    name: jenkins-edit
    namespace: ${PROJECT_NAME}
  roleRef:
    name: edit
  subjects:
  - kind: ServiceAccount
    name: jenkins
  userNames:
  - system:serviceaccount:${PROJECT_TEMPLATE_NAME}-jenkins:jenkins
- apiVersion: v1
  kind: RoleBinding
  metadata:
    labels:
      provider: fabric8
      project: fabric8-online-team
      version: 1.0.91
      group: io.fabric8.online.packages
    name: jenkins-view
    namespace: ${PROJECT_NAME}
  roleRef:
    name: view
  subjects:
  - kind: ServiceAccount
    name: jenkins
  userNames:
  - system:serviceaccount:${PROJECT_TEMPLATE_NAME}-jenkins:jenkins
